root: "logs"
exp_name: "taic_instance"
task: "instance"
dataset_path: "/data/coco2017"
base_codec: "./checkpoints/base_codec/base_codec_1.pth.tar"
checkpoint: null
epochs: 35
learning_rate: 1.0e-4
gpu_id: 0
quality_level: 1
lmbda: 0.0035
num_workers: 8
batch_size: 80
test_batch_size: 1
patch_size: 256
cuda: true
save: true
seed: 42
pretrained_backbone: true
out_channels: 128
align_mode: "fpn"
